[package]
name = "mauricebarnum-oxia-cmd"
version = "0.1.0"
edition.workspace = true

[dependencies]
mauricebarnum-oxia-client = { path = "../client" }
mauricebarnum-oxia-common = { path = "../common" }

[lints]
workspace = true
