#!/bin/bash
# Fetches and replaces the .proto files from upstream and writes the revision used.

set -euo pipefail

# Config
# ------

upstream_repo="https://github.com/oxia-db/oxia"
upstream_dir="proto"
src_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
local_proto_dir="${src_dir}/proto"

# Temporary location
# ------------------
#
tmp_dir="$(mktemp -d)"
cleanup() {
    rm -rf "${tmp_dir}"
}
trap cleanup EXIT


echo "[update_proto] Cloning ${upstream_repo}..."
git clone --depth=1 --filter=blob:none --sparse "${upstream_repo}" "${tmp_dir}/oxia"
git -C "${tmp_dir}/oxia" sparse-checkout set "${upstream_dir}"

echo "[update_proto] Copying proto files..."
cp -v "${tmp_dir}/oxia/${upstream_dir}/"*.proto "${local_proto_dir}/"

#upstream=https://github.com/oxia-db/oxia

echo "[update_proto] Saving upstream info..."
rev=$(git -C "$tmp_dir/oxia" rev-parse HEAD)
echo "${upstream_repo}/tree/${rev}" > "${local_proto_dir}/UPSTREAM"

echo "[update_proto] Building with new proto file..."
cargo build --all-targets

echo "[update_proto] Staging changes..."
cd "${src_dir}"
git add -A "${local_proto_dir}"

