[package]
name = "oxia-bin-util"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[build-dependencies]
base16ct = { version = "0.2.0", features = ["alloc"] }
is_executable = "1.0.4"
sha2 = "0.10.9"
walkdir = "2.5.0"
