#!/bin/bash

set -x
set -e
set -o pipefail

version="$(basename $(cat ../common/proto/UPSTREAM))"
cd go
go get "github.com/oxia-db/oxia@${version}"
go mod tidy
go mod vendor
cargo build
git add -A -- .
