[package]
name = "mauricebarnum-oxia-common"
version = "0.1.0"
publish = false
edition.workspace = true
license = "Apache-2.0"

[dependencies]
bytes = "1.12.1"
prost = "0.14.4"                                                       # If using Protobuf
prost-types = "0.14.4"
tonic = { version = "0.14.6", features = ["gzip", "channel", "zstd"] }
tonic-prost = "0.14.6"
grpc = "0.9.0"
grpc-protobuf = "0.9.0"
protobuf = "4.34.0-release"

[build-dependencies]
prost-build = "0.14"
tonic-prost-build = "0.14.6"
grpc-protobuf-build = "0.9.0"

[lints.clippy]
all = "allow"
pedantic = "allow"
