name: build-docker-image

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'build/Dockerfile'
      - '.github/workflows/docker-image.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'build/Dockerfile'
      - '.github/workflows/docker-image.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1' # weekly

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/rust-build

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            # Only tag "latest" if building on main
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/rust-build:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/rust-build:cache,mode=max

